export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const DECREMENT_PRODUCT = 'DECREMENT_PRODUCT';
export const INCREMENT_PRODUCT = 'INCREMENT_PRODUCT';
